[versions]
agp = "9.4.0"
kotlin = "2.4.20"
ksp = "2.3.12"
compose = "2026.03.00"
room = "2.8.5"
media3 = "1.11.1"
[libraries]
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
